name: Label PRs
on:
  pull_request:
    branches: ["main"]
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const labelMap = new Map([
            ["feat", "enhancement"]
            ]) 
            github.rest.issues.addLabels({
              issue_number: ${{ github.event.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: [labelMap.get( ${{ github.event.pull_request.title }}.split("(")[0] ))]
            })
