name: Label PRs
on:
  pull_request:
    branches: ["main"]
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const labelMap = new Map([
            ["feat", "enhancement"]
            ]) 
            github.rest.pulls.addLabels({
              pull_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: [labelMap.get(context.payload.pull_request.title.split("(")[0])],
            });
